### ISSUE TITLE
CORS 관련 설정 완료

### ISSUE THREAD

**Issue by golony6449** [ssky10/go100#17]
Cross-Origin Resource Sharing 를 모든 호스트에서 가능하도록 서버에 설정했습니다.

다만, `django-cors-headers` 모듈의 버그인지는 모르겠으나
요청할때, 자신의 호스트 이름을 헤더의 `Origin`에 넣어주시기 바랍니다.

그렇지 않으면 응답에 `Access-Control-Allow-Origin`이 포함되지 않습니다.

### 예
* 상황: 8000번 포트에서 동작하는 로컬호스트에서 `golony.dev`에 요청
* 추가할 헤더: `Origin: "127.0.0.1:8000"`

### 형식
* 상단의 요청은 헤더에 `Origin`을 포함하지 않고 요청한 것
* 하단의 요청은 헤더에 `Origin`을 포함한 것

![캡처1](https://user-images.githubusercontent.com/10653376/57584405-e0ee7e00-7515-11e9-8d91-14587be73ff9.JPG)

**Comment by ssky10** [comment]
`api/login`에 post로 접속할 경우 500error 발생
![image](https://user-images.githubusercontent.com/7812961/57892774-3363cd80-787b-11e9-8778-5d0ab2607c49.png)

![image](https://user-images.githubusercontent.com/7812961/57892600-75404400-787a-11e9-9a66-d944351318d2.png)

**Comment by golony6449** [comment]
제 쪽에서는 정상적으로 동작하는 것으로 보입니다.
![image](https://user-images.githubusercontent.com/10653376/57897937-f8b95f80-7891-11e9-907c-f20c8591fd3a.png)

혹시 JSON 인코딩 할때, 키 값에도 `"키"` 처리를 해주셨나요?

혹시 재현 가능하면 
![image](https://user-images.githubusercontent.com/10653376/57898064-66fe2200-7892-11e9-8033-e6b48769c4e4.png)
`Local Variables`를 클릭해서 변수 내용까지 다시 첨부해주실수 있으신가요?

**Comment by ssky10** [comment]
> 제 쪽에서는 정상적으로 동작하는 것으로 보입니다.
> ![image](https://user-images.githubusercontent.com/10653376/57897937-f8b95f80-7891-11e9-907c-f20c8591fd3a.png)
> 
> 혹시 JSON 인코딩 할때, 키 값에도 `"키"` 처리를 해주셨나요?
> 
> 혹시 재현 가능하면
> ![image](https://user-images.githubusercontent.com/10653376/57898064-66fe2200-7892-11e9-8033-e6b48769c4e4.png)
> `Local Variables`를 클릭해서 변수 내용까지 다시 첨부해주실수 있으신가요?

일단 지금은 정상적으로 동작하는거 확인했습니다. 다만 코드 변경사항도 없는데 어제, 오늘 해당 오류가 왜 발생했는지 모르겠네요. 일단 그 당시에 서버에서 반환한 내용 html파일로 옮겨놓은 파일입니다.
[error.html](https://gnuackr0-my.sharepoint.com/:u:/g/personal/ssky10_gnu_ac_kr/Ea0vfwarhmlHljk-EIx9AE4BAOqoyrAauI2HA5v4a23LUA?e=MHLjEU)

**Comment by golony6449** [comment]
@

> > 제 쪽에서는 정상적으로 동작하는 것으로 보입니다.
> > ![image](https://user-images.githubusercontent.com/10653376/57897937-f8b95f80-7891-11e9-907c-f20c8591fd3a.png)
> > 혹시 JSON 인코딩 할때, 키 값에도 `"키"` 처리를 해주셨나요?
> > 혹시 재현 가능하면
> > ![image](https://user-images.githubusercontent.com/10653376/57898064-66fe2200-7892-11e9-8033-e6b48769c4e4.png)
> > `Local Variables`를 클릭해서 변수 내용까지 다시 첨부해주실수 있으신가요?
> 
> 일단 지금은 정상적으로 동작하는거 확인했습니다. 다만 코드 변경사항도 없는데 어제, 오늘 해당 오류가 왜 발생했는지 모르겠네요. 일단 그 당시에 서버에서 반환한 내용 html파일로 옮겨놓은 파일입니다.
> [error.html](https://gnuackr0-my.sharepoint.com/:u:/g/personal/ssky10_gnu_ac_kr/Ea0vfwarhmlHljk-EIx9AE4BAOqoyrAauI2HA5v4a23LUA?e=MHLjEU)


아 원인 파악 했습니다.
제가 서버에서 실행할때 `&` 키워드로 백그라운드에서 실행했는데
이 상태에서 SSH를 로그아웃하면 출력할 터미널이 존재하지 않아
`IOError: [Errno 5] Input/output error` 
에러가 발생하는 것으로 보입니다.

지금은 제가 SSH에 로그인한 상태라 정상적으로 동작하는것으로 보입니다.
사실 로그로 쌓아야 된다고 생각하고 있어서, stdout을 파일로 지정하는 것으로 해결하겠습니다.

**Comment by golony6449** [comment]
* 관련 자료: https://stackoverflow.com/questions/52376942/python-ioerror-errno-5-input-output-error
