### ISSUE TITLE
Admin Page에 접근할 수 없음

### ISSUE THREAD

**Issue by golony6449** [ssky10/go100#18]
5월 12일자 기준 웹앱 적용을 마쳤습니다.

이전에 언급한, <b>새로고침 시도시, 해당하는 URL 없음 에러발생</b>은 더 이상 발생하지 않습니다만,
`golony.dev/admin`에 접근을 시도하면 아래와 같이 Django admin 페이지가 아닌 React 앱이 로드됩니다.

admin page는 앞으로 기능개발할때 종종 확인 목적으로 사용될 것으로 예상되어서
`/admin` 경로는 예외처리 부탁드리겠습니다.

![image](https://user-images.githubusercontent.com/10653376/57585462-83612e00-7523-11e9-8e67-55e8830b890d.png)

**Comment by ssky10** [comment]
관리자 페이지 주소는 golony.dev/admin/ 으로 확인됨
(추가:리엑트는 그러한 예외 처리 불가할것으로 예상)

**Comment by ssky10** [comment]
service worker 문제로 확인됨.
1차적 해결방안으로는 build시 자동 생성되는 `service-worker.js` 파일 내부의
```
orkbox.routing.registerNavigationRoute("/index.html", {
  blacklist: [/^\/_/,/\/[^\/]+\.[^\/]+$/],
});
```
을
```
orkbox.routing.registerNavigationRoute("/index.html", {
  blacklist: [/^\/_/,/\/[^\/]+\.[^\/]+$/,/admin/],
});
```
으로 변경

**Comment by ssky10** [comment]
`sw-fix.js` 파일 별도로 작성하여 빌드시 해당 스크립트가 자동으로 실행되어 `build/service-worker.js` 파일을 직접 접근하여 파일 수정 후 덮어쓰는 방식으로 오류 해결함.
(위 방법으로도 접근 불가시 해당 이슈 reopen바람)
