### ISSUE TITLE
[API]공지사항 게시판

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#20]
# API 요청
1. 요청 API 주소 : /api/post/getNoticePosts
2. 서비스 내용 : 공지사항 게시물 출력
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class | int | 학급 구분자 | - 
BoardIdx | int | 학급 게시판 구분자 | 0일 경우 Main 게시판, 2일 경우 과제 게시판, 그 외 int 예외

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
userID or userName | String | 공지 게시자 | -
date | Date or Datetime | 공지 게시 날짜 | -
noticeContents | String | 공지 내용 | -

**Comment by golony6449** [comment]
특정 공지 1개만 보내드리면 되는건가요?

**Comment by golony6449** [comment]
특정한 공지 1개에 대한 정보를 보내도록 구현했습니다.

**Comment by golony6449** [comment]
https://gitlab.com/golony6449/go100/blob/develop/url_design.md

**Comment by yg3988** [comment]
이제 봤습니다. 특정 공지 1개가 아니라  공지 DB에 있는 레코드 다 가져오는 식으로 해줘요

요청 API 주소도 수정했습니다.

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class | int | 학급 구분자 | - 
BoardIdx | int | 학급 게시판 구분자 | 0일 경우 Main 게시판, 1일 경우 공지 게시판, 그 외 int 예외

이렇게 수정합니다.

**Comment by golony6449** [comment]
REST 명명 규칙에 따라, classroom 관련 기능은 `/api/classroom` 하단에 위치하게 하겠습니다.

**Comment by golony6449** [comment]
요청사항 적용 했습니다. 

요청하신 데이터 말고도 필요하다고 생각되는 데이터를 더 추가했습니다.

자세한 내용은 URL 문서를 참고해주세요.

https://gitlab.com/golony6449/go100/blob/develop/url_design.md
