### ISSUE TITLE
[API] 문제 가져오기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#21]
# API 요청
1. 요청 API 주소 : `api/exam/getQuestion`
2. 서비스 내용 : DB에 저장된 문제 1개 이상을 받아옴
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
subject | int | 받아올 문제의 과목코드 | 필수
num | int | 받아올 문제의 개수 | code값이 -1이 아닌 경우 반드시 1
code | int | 특정 문제를 요청하는 경우 문제의 고유번호 | -1인 경우 해당과목의 랜덤한 문제 반환

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID| 성공시
msg | String | 오류 메시지 | 실패시만 필요
num | int | 반환된 문제의 개수 | -
data | array | 반환된 문제 집합 | 아래 문제 형식 참조

- 문제 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 문제고유번호 | -
ID | String | 문제작성자 ID | - 
type | bool | 문제 타입 | (F:단답형/T:객관식)
context | String | 문제내용 | - 
example | array | 객관식인 경우 보기 집합 | 아래 보기 형식 참조

- 보기 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 보기번호 | -
Context | String | 보기 문자 | -

**Comment by ssky10** [comment]
수정사항으로 반환 문제 형식에 ID값 추가 되었습니다.

**Comment by Y0ung-i1** [comment]
3. 전송데이터 첫번째 'name' 문의
넘어오는 subject가 '과목코드'로 처리할시 프론트에서 과목코드를 알지 못할것 같은데 어떻게 처리 할지?
'과목명'으로 넘어오면 그냥 그대로 처리하면 되는데 이 방법은 어떤가요?

**Comment by ssky10** [comment]
> 1. 전송데이터 첫번째 'name' 문의
>    넘어오는 subject가 '과목코드'로 처리할시 프론트에서 과목코드를 알지 못할것 같은데 어떻게 처리 할지?
>    '과목명'으로 넘어오면 그냥 그대로 처리하면 되는데 이 방법은 어떤가요?
@Y0ung-i1 
1. 여기서 말하는 과목코드는 프론트앤드부분에서 정한 임의의 값입니다.
    예를 들어 중학국어는 100, 공통국어는 101, ....
2. 따라서 과목코드는 오히려 프론트에서는 파악할 수 있지만 서버에서 파악하지 못하는 구조였습니다.
    물론 과목명으로 변경하셔도 크게 상관은 없습니다.

**Comment by ssky10** [comment]
@Y0ung-i1  @golony6449 
지금 현재 반환되는 값을 보면 아래와 같이 나와있는데
```
{
  "status": true,
  "data": [
    {
      "code": 1, 
      "ID": "parkseongheum", 
      "type": false, 
      "context": "\ub2e4\uc74c 2\ucc28 \ubc29\uc815\uc2dd\uc758 \ud574\ub97c \uad6c\ud558\uace0 \uc774\ub97c \uc544\ub798\uc640 \uac19\uc774 \ucc98\ub9ac\ud558\uc2dc\uc624",
      "example": [
        {"ex_code": 1, "ex_context": "1"}, 
        {"ex_code": 2, "ex_context": "2"}, 
        {"ex_code": 3, "ex_context": "3"}, 
        {"ex_code": 4, "ex_context": "4"}, 
        {"ex_code": 5, "ex_context": "5"}
      ]
    }
  ]
}
```
1. num에 해당하는 키값이 빠져있습니다.
2. 또한 회의시간에도 말씀드렸듯 모든페이지에서 user_token을 전송하여 사용자 정보(ID,교사유무)를 저송받아야 하며 특히 해당페이지에서 이 부분은 필수적 요소 입니다.
3. 제가 요청한 사항에 대해 조금 오해가 있으셨던거 같은데 제가 요청한 num의 개수 보다 현재 저장된 문제의 개수가 더 작을때는 에러를 반환하는 것이 아니라 **num개수 이내의 전달 가능한 모든 문제를 전달** 해야 합니다.(예를 들어 요청이 num이 5였지만 DB 검색결과 3개의 문제만 존재하는 경우 반환시 num값을 3으로 하여 data에 3개의 문제 전부 전송)
4. 그리고 첨부된 img도 추가적으로 전송 부탁드립니다.
5. 마지막으로 작성하신 레퍼런스 문서랑 변수명이 일치하지 않는 부분이 너무 많네요..... 레퍼런스 수정 부탁드립니다. 디버깅하기 힘들어요ㅠㅠ

**Comment by golony6449** [comment]
키 수정 요청합니다.

혼동 방지를 위해 `type`을 `choiceable`로 수정해 사용해주세요.
값은 수정사항 없습니다.

@ssky10

**Comment by ssky10** [comment]
@golony6449 , @Y0ung-i1 
api요청시 505 Bad Gateway 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/7812961/58366656-7fb0ac80-7f10-11e9-8b02-08fa4f338f69.png)
![image](https://user-images.githubusercontent.com/7812961/58366666-b8e91c80-7f10-11e9-9991-374982d00db6.png)

타 api는 정상작동하는 상황으로 봐서는 해당 코드에서 무한 루프나 이런 유사한 상황으로 빠지는 부분이 있는듯 합니다. 확인 부탁드립니다.

**Comment by golony6449** [comment]
바로 확인해보겠습니다.

**Comment by golony6449** [comment]
원인 파악되었습니다.

20분 이내로 해결가능할것으로 예상됩니다.

**Comment by golony6449** [comment]
문제 해결 완료되었습니다.

일단 제가 동일한 내용
```json
{"subject": "201", "num": "5", "code": "-1", "user_token": "IPoUBaOiGFqBrhmkVnwwdSqhFuMETN"}
```
으로 요청을 보냈을때는 정상 동작함을 확인했습니다.

테스트 후 피드백 부탁드립니다.

### 테스트 수행 결과
![image](https://user-images.githubusercontent.com/10653376/58367118-5266fd00-7f16-11e9-9127-a416297f7b04.png)

**Comment by ssky10** [comment]
@golony6449 
해당문제 오류는 해결됨을 확인했습니다.
그런데 문제가 하나도 없는 과목의 요청에서 다음과 같은 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/7812961/58367421-0453f880-7f1a-11e9-8293-2c01438f2e20.png)
![image](https://user-images.githubusercontent.com/7812961/58367435-32d1d380-7f1a-11e9-828e-ca914cdd0075.png)

**Comment by golony6449** [comment]
확인해보겠습니다.

**Comment by golony6449** [comment]
늦어서 죄송합니다.

해당 부분은 문제를 랜덤하게 요청하는 경우에 과목이 존재하지 않는 경우에 대한 예외처리가 되지 않아 발생한 문제였습니다.

테스트 후 피드백 부탁드립니다.

**Comment by ssky10** [comment]
정상작동 확인했습니다.

**Comment by ssky10** [comment]
![image](https://user-images.githubusercontent.com/7812961/58384307-43b63e00-801b-11e9-8876-2d0c4775f627.png)
![image](https://user-images.githubusercontent.com/7812961/58384312-503a9680-801b-11e9-81d1-3d062dcaa03d.png)
 수정전 발생했던 기능상 에러가 다시 발생합니다. 확인 부탁드립니다.

**Comment by ssky10** [comment]
![image](https://user-images.githubusercontent.com/7812961/58384331-8415bc00-801b-11e9-9c5c-ed68b8de4488.png)
![image](https://user-images.githubusercontent.com/7812961/58384333-8c6df700-801b-11e9-92dc-5ed9b73e9afb.png)

이전에 발생했던 기능상 에러가 다시 발생합니다. 확인 부탁드립니다.

**Comment by golony6449** [comment]
Merge 중 발생한 문제였습니다.

조금전 수정, 테스트 완료했습니다.
