### ISSUE TITLE
[API] firebase 토큰 전송

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#22]
# API 요청
1. 요청 API 주소 : `api/setToken`
2. 서비스 내용 : firebase클라우드 메시지 전송을 위한 클라이언트 토큰값 전달
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
token | String | 토큰값 | - 

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID| 성공시
msg | String | 오류 메시지 | 실패시만 필요

**Comment by golony6449** [comment]
구현했습니다. ^^

자세한 내용은 URL 문서를 참고해주세요.

https://gitlab.com/golony6449/go100/blob/develop/url_design.md

**Comment by golony6449** [comment]
성공시 ID 반환 부분이 빠져있어서 추가했습니다.
