### ISSUE TITLE
[API] 과제 가져오기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#25]
# API 요청
1. 요청 API 주소 : api/post/getWorkPosts
2. 서비스 내용 : 과제 내용을 가져옴
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class | int | 학급 구분자 | - 
BoardIdx | int | 학급 게시판 구분자 | 0일 경우 Main 게시판, 2일 경우 과제 게시판, 그 외 int 예외

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
subject | String | 과제 과목명 | 과제 과목 | -
tilte | String | 과제 명| 과제 명 | -
DeadLine | Datetime | 과제 기한 or 제출 기간 | -

**Comment by golony6449** [comment]
과제 전체 리스트, 각각의 과제

2개의 API 모두 구현하겠습니다.

**Comment by Y0ung-i1** [comment]
각 과목별 개설된다고 생각되어 과제 과목명을 반환데이터에서 제하고자 합니다.

**Comment by golony6449** [comment]
> 각 과목별 개설된다고 생각되어 과제 과목명을 반환데이터에서 제하고자 합니다.

@yg3988

**Comment by golony6449** [comment]
구현 완료했습니다.

저희쪽에서 테스트 결과로는 정상동작함을 확인했습니다.

확인 후 피드백 부탁드립니다.
