### ISSUE TITLE
[API] firebase 토큰 삭제 요청

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#26]
# API 요청
1. 요청 API 주소 : `api/deleteToken`
2. 서비스 내용 : 등록된 토큰 제거
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
token | String | 삭제할 토큰의 값 | - 

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | Bool | 토큰삭제 성공여부 | -

**Comment by golony6449** [comment]
구현 완료했습니다.

내용은 URL 문서 참고 부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design.md

**Comment by golony6449** [comment]
아, 그리고, 인증관련해서 오류가 떠서 테스트는 못해봤는데, 혹시 동작하지 않는 부분이 있다면 다시 이슈 오픈해주세요.

**Comment by ssky10** [comment]
토큰 삭제시 다음과 같은 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/7812961/58171467-0aa36400-7cd1-11e9-84f6-6d07c0164ce4.png)

전송된 내용은 아래와 같으며
![image](https://user-images.githubusercontent.com/7812961/58171532-30c90400-7cd1-11e9-8a5a-d1417c3efa61.png)
```
{
  "Origin":"localhost",
  "user_token":"cgHYoiJrZewjHanJcUByCgtigZqktN",
  "fcm_token":"e8WLtEar_28:APA91bHU5GYmTYmJSsLCMFaD21EWsMdDfiUuk8J3EmpSxbT72QiDfQKPr5PjtExD9bp6xl2cBbO286aa6ml8p9fDo_AO-SIExp7dY8FvjhPDGBZDz8DZC_gxWdBY1B1MnbZJOVsfbWTR"
}
```

실제 DB에 저장된 내용도 서로 일치합니다.
![image](https://user-images.githubusercontent.com/7812961/58171744-a46b1100-7cd1-11e9-8a43-71e329323484.png)

**Comment by golony6449** [comment]
늦어서 죄송합니다.

관련 부분 수정했습니다. 확인 부탁드립니다.
