### ISSUE TITLE
[API] 로그아웃 수정

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#27]
# API 수정 요청
1. 요청 API 주소 :  `api/auth/logout`
2. 서비스 내용 : 프론트 부분에서 가지고 있는 ID정보가 없으므로 로그아웃시 전송데이터 없음
3. 전송데이터

   - 없음

4. 반환데이터

   - 기존과 동일

**Comment by golony6449** [comment]
아.. 이미 구현되어있는 내용이었습니다.

URL 문서 수정하겠습니다.

혼동을 드려 죄송합니다.
