### ISSUE TITLE
로그인 세션관련 버그

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#28]
서버에 올라간 코드는 세션을 이용한 로그인 유지가 정상적으로 작동하나 리엑트 테스트 서버로 실행시 세션이 유지되지 않는것 같음.

로그인 후 파이어베이스 관련 기능 동작시 아래의 오류메시지 출력
![image](https://user-images.githubusercontent.com/7812961/57972485-43dc8b00-79d6-11e9-83d2-ffdd4d7591cf.png)

또한 서버에 있는 사이트에 로그인시 로그인된 사용자는 다시 로그인시 이미 로그인 된것으로 에러처리 되지만 로컬호스트로 동작시 계속해서 로그인이 가능함

**Comment by golony6449** [comment]
1차적인 원인 파악 끝났습니다.

## 빌드한 결과물을 서버에 적용
* 여러번 요청을 보내도 CBV 내부의 `request.session._session_key`의 값이 변하지 않음
* 세션에 저장되는 로그인 관련 값이 보존됨

## `yarn start` 로 실행한 뒤 서버에 요청을 보내는 경우
* 요청할때 마다 CBV 내부의 `request.session._session_key`의 값이 변함
* 매번 새로운 요청으로 간주, 로그인되지 않은것으로 보임

**Comment by golony6449** [comment]
다만, 제가 세션 부분을 사실상 블랙박스처럼 쓰고 있어서

해결에는 시간이 좀 걸릴듯 합니다. ㅠㅠ

**Comment by golony6449** [comment]
@ssky10 

쿠키에 sessionid가 저장이 되지 않아서, 매번 새로운 세션이 발급되는것 같습니다.

## yarn start로 실행한 테스트 서버
![image](https://user-images.githubusercontent.com/10653376/57979232-d83a0280-7a55-11e9-941a-081443a9194a.png)

## `golony.dev`
![image](https://user-images.githubusercontent.com/10653376/57979236-ebe56900-7a55-11e9-94bb-1ba356238745.png)

**Comment by golony6449** [comment]
Issue Close 하겠습니다.

자세한 내용은 위에서 참조된
https://github.com/ssky10/go100/issues/31을 참고해주세요.
