### ISSUE TITLE
[API] 로그인 회원의 수강중인 클래스 리스트 요청

### ISSUE THREAD

**Issue by sjheispretty** [ssky10/go100#30]
# API 요청
1. 요청 API 주소 :  /api/post/getClassList
2. 서비스 내용 : 회원의 클래스 리스트 출력 
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
userID| String | 로그인한 회원 아이디| - 
userPassword| String | 비밀번호 | - 

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
Context| String | 리스트 | -
Status| Boolean| 성공 여부 | -

**Comment by ssky10** [comment]
아이디와 비밀번호는 프론트앤드에서 보관하지 않기때문에 전송이 불가합니다.

**Comment by golony6449** [comment]
@sjheispretty 

지금 사용자 토큰을 이용하도록 변경되었는데

혹시 로그인 창에서 전달받은 토큰이 있으면 그것만 전달해주시면 처리할 수 있습니다.

일단 그렇게 구현할까요?

**Comment by golony6449** [comment]
@sjheispretty 

구현완료했습니다.

주소와 입출력 키에서 수정사항이 있으니, 자세한 내용은 링크 참조 부탁드립니다.
https://gitlab.com/golony6449/go100/blob/develop/url_design.md

혹시 오류가 있으면 다시 `reopen`해주세요.
