### ISSUE TITLE
[API] 문제 작성하기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#32]
# API 요청
1. 요청 API 주소 : `api/exam/writeQuestion`
2. 서비스 내용 : DB에 문제를 저장함
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
token | String | 현재 로그인된 사용자 토큰 | -
choiceable | bool | 문제 타입 | (F:단답형/T:객관식)
subject | int | 작성 문제의 과목코드 | -
context | String | 문제내용 | - 
img | file | 문제 이미지 | 옵션
answer | String | 문제 정답 | 단답형이면 단답형정답, 객관식이면 객관식 답 인덱스 번호
explanation | String | 문제해설 | -
example | array | 객관식인 경우 보기 집합 | 아래 보기 형식 참조

- 보기 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 보기번호 | -
Context | String | 보기 문자 | - 

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID | 성공시
msg | String | 오류 메시지 | 실패시만 필요
code | int | 성공시 문제의 고유번호 | -

**Comment by golony6449** [comment]
키 수정 요청합니다.

혼동 방지를 위해 `type`을 `choiceable`로 수정해 사용해주세요.

@ssky10

**Comment by ssky10** [comment]
전송 데이터에 img 추가 되었습니다.

**Comment by golony6449** [comment]
구현 및 서버에 배포를 마쳤습니다.

객관식, 주관식 각각에 대해 테스트 진행했는데 정상 동작함을 확인했습니다.

확인 후 피드백 부탁드립니다.

**Comment by golony6449** [comment]
https://gitlab.com/golony6449/go100/blob/develop/url_design
