### ISSUE TITLE
[API] 문제 정답확인하기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#34]
# API 요청
1. 요청 API 주소 : `api/exam/markQuestion`
2. 서비스 내용 : 문제를 풀고 난 뒤 답을 체크
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
token | String | 현재 로그인된 사용자 토큰 | -
code | int | 문제의 고유번호 | -
marking | String | 문제 정답 | 사용자가 선택(입력)한 정답의 값(객관식인 경우 인덱스 번호)

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID | 성공시
msg | String | 오류 메시지 | 실패시만 필요
code | int | 문제의 고유번호 | -
explanation | String | 문제해설 | -
answer | String | 문제 정답 | -

**Comment by golony6449** [comment]
해당 API 구현완료했습니다.

저희 쪽에서 테스트 했을때는 정상 응답함을 확인했습니다

확인후 피드백 부탁드립니다.

**Comment by golony6449** [comment]
@ssky10 

다만, 기능상은 아니지만 사소한 문제가 하나 존재합니다.

![image](https://user-images.githubusercontent.com/10653376/58382482-8ff68380-8005-11e9-8815-9c11c65277ea.png)

answer 부분이 전달되기 때문에, 사용자가 개발자도구로 패킷을 뜯어보면, 정답확인이 가능합니다.

**Comment by ssky10** [comment]
@golony6449 
위의 api는 사용자가 정답을 입력한 뒤에 받아오는 부분이며 사용자가 답을 제출한 이후는 어차피 사용자에게 답을 알려주므로 패킷을 뜯어보는것이 의미 없을 것으로 예상됩니다.

위 구현사항은 빠른시일내 확인 후 피드백드리겠습니다.

**Comment by Y0ung-i1** [comment]
@golony6449 중복여부 체크 후 중복시 오답노트에 저장하지않도록 수정하였습니다.
