### ISSUE TITLE
인증 파트 수정했습니다.

### ISSUE THREAD

**Issue by golony6449** [ssky10/go100#35]
늦어져서 죄송합니다.

인증관련 부분 수정이 끝났습니다.

`/login`, `/logout`, `/add_token` API 에서 변경사항이 있으니 참고부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design.md

**Comment by ssky10** [comment]
@golony6449 
로그인 시도시 아래와 같은 에러 발생합니다. 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/7812961/58100380-7b3a7a00-7c18-11e9-9d06-e6bcc0248b7e.png)
[html파일](https://gnuackr0-my.sharepoint.com/:u:/g/personal/ssky10_gnu_ac_kr/EXQOt_QdAoVPsMcVAMQOH70BhehEwZR9ay323nkVAgC0Pw?e=kvKNbM)

**Comment by golony6449** [comment]
아 죄송합니다.

구현 해놓고 모델을 변경한 부분이 있는데, 미쳐 수정하지 못한것 같습니다.

바로 수정하겠습니다.

**Comment by golony6449** [comment]
수정완료 했습니다.

확인해보시고, 정상동작하면 Close 해주시고, 지속되면, 피드백 부탁드립니다.

**Comment by ssky10** [comment]
@golony6449 
이젠 다른 에러가 뜨네요....;;
![image](https://user-images.githubusercontent.com/7812961/58103359-cc00a180-7c1d-11e9-9416-a50a1965ae0a.png)
[html파일](https://gnuackr0-my.sharepoint.com/:u:/g/personal/ssky10_gnu_ac_kr/Ec2uUhC5QuxAt0TWs2sTu1oBoMNdGbsHZYBylFQyWAiSYw?e=umxJdG)

**Comment by golony6449** [comment]
흑흑 총재적 난국이군요 ㅠㅠ 잠시만기다려주세요.

갑자기 DB 자체가 죽어버린 느낌이라서 조금 걸릴듯 합니다.

20분 안에 해결해볼게요.

**Comment by golony6449** [comment]
수정 완료했습니다.

피드백 부탁드립니다.

**Comment by ssky10** [comment]
@golony6449 
정상동작 확인했습니다. 수고하셨습니다.
