### ISSUE TITLE
API 수정 완료

### ISSUE THREAD

**Issue by golony6449** [ssky10/go100#38]
지금까지 작성한 모든 API에서 반환값에 `is_teacher`, `id` 를 추가했습니다.

또한, 용어는 `user_token`, `fcm_token`으로 통일하겠습니다.

자세한 변경사항은 [서버쪽 Repo](https://gitlab.com/golony6449/go100/blob/develop/url_design.md) 참고 부탁드립니다.

**Comment by golony6449** [comment]
test

**Comment by Y0ung-i1** [comment]
telegram test

**Comment by ssky10** [comment]
@golony6449 
로그인에 해당하는 부분에 서버쪽 Repo랑 일치하지 않는 부분이 일부 있네요.
일단 전달 값이 id랑 password인데 email도 포함되어 있어 3개의 값을 모두 날려야 정확하게 전송이 됩니다.

그리고 받아오는 값도 id로 바뀐거 같은데 문서는 nickname으로 그대로 되어있습니다.

수정부탁드립니다!

**Comment by yg3988** [comment]
확인했습니다

**Comment by golony6449** [comment]
앗 죄송합니다. 

가야할 곳이 있어서 급하게 수정했는데 미쳐 확인하지 못한 부분이 있네요.

지금 바로 수정하겠습니다.

**Comment by golony6449** [comment]
@ssky10 

해당 부분 수정했습니다.

다음부터는 누락부분 없이 꼼꼼히 신경쓰도록 하겠습니다.

**Comment by ssky10** [comment]
@golony6449 
확인했습니다! 수고하셨습니다.
