### ISSUE TITLE
[API] 오답노트 가져오기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#40]
# API 요청
1. 요청 API 주소 : `api/exam/note`
2. 서비스 내용 : 문제 풀이 후 틀린 문제 모두 가져옴
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인사용자의 토큰 | - 

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID | 성공시
msg | String | 오류 메시지 | 실패시만 필요
num | int | 반환된 문제의 개수 | -
data | array | 반환된 문제 집합 | 아래 문제 형식 참조

- 문제 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 문제고유번호 | -
ID | String | 문제작성자 ID | - 
subject | int | 문제의 과목코드 | -
type | bool | 문제 타입 | (F:단답형/T:객관식)
img | String | 문제에 포함된 이미지 | -
context | String | 문제내용 | - 
example | array | 객관식인 경우 보기 집합 | 아래 보기 형식 참조

- 보기 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 보기번호 | -
context | String | 보기 문자 | -

**Comment by golony6449** [comment]
이 기능은 문제 풀이 관련 이슈 먼저 해결 된 뒤, 구현하겠습니다.

**Comment by golony6449** [comment]
@ssky10
문의사항이 있습니다.
저 오답노트라는 것이, 특정 사용자가 지금까지 틀린 모든 문제에 대한 정보를 말하는건가요?

아니면 문제 N개를 가져온 뒤, 푼 다음, 방금 푼 N개의 문제 중 틀린 것에 대한 정보를 말하는 건가요?

**Comment by ssky10** [comment]
@golony6449
지금까지 풀었던 모든 문제 중 틀렸던 문제를 말합니다

**Comment by golony6449** [comment]
@ssky10 

알겠습니다. 감사합니다.

**Comment by golony6449** [comment]
구현 완료했습니다.

`go100` 계정으로 임시 레코드를 추가해 테스트 결과, 정상적으로 응답함을 확인했습니다.

확인 후 피드백 부탁드립니다.

https://gitlab.com/golony6449/go100/tree/develop/url_design

**Comment by ssky10** [comment]
정상동작 확인했습니다.

**Comment by ssky10** [comment]
오답노트의 값을 가져올때는 내가 틀린 이력을 가져오는것이 목적이 아니라 내가 틀렸던 문제를 다시 풀어보는것이 목적이므로 같은 문제를 중복해서 틀렸을 경우에도 해당문제는 1번만 보내도록 수정 부탁드립니다.
