### ISSUE TITLE
[API] 첨삭 작성하기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#41]
# API 요청
1. 요청 API 주소 : `api/exam/writeSolution`
2. 서비스 내용
  강사가 해당 문제에 대한 평가(풀이) 작성
  (1차적으로 프론트엔드부에서도 is_teacher값을 확인하지만 서버에서도 추가적으로 체크 바람)
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인된 사용자의 토큰값 | - 
code | int | 평가하고자 하는 문제의 고유번호 | - 
score | int | 해당문제에 대한 평가 점수 | 0~10의 값
context | String | 문제에 대한 평가 및 풀이 | -
img | file | 평가 및 풀이 이미지 | 옵션

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | boolean | 성공여부 | - 
ID | String | 현재 로그인된 사용자 ID| 성공시
msg | String | 오류 메시지 | 실패시만 필요

**Comment by golony6449** [comment]
구현 및 테스트 완료했습니다.

확인 후 피드백 부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/exam_url_design.md
