### ISSUE TITLE
[API] 내가 작성한 문제 가져오기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#44]
# API 요청
1. 요청 API 주소 : `api/exam/myQuestion`
2. 서비스 내용 : 내가 작성한 문제 전체리스트를 가져옴
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인된 사용자의 토큰 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
ID | string | 로그인된 사용자ID | -
questions | array | 문제리스트 | 아래 문제 형식 참조

- 문제 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 문제고유번호 | -
choiceable | bool | 문제 타입 | (F:단답형/T:객관식)
subject | int | 문제의 과목코드 | -
context | String | 문제내용 | - 
img | file | 문제 이미지 | 옵션
answer | String | 문제 정답 | 단답형이면 단답형정답, 객관식이면 객관식 답 인덱스 번호
explanation | String | 문제해설 | -
example | array | 객관식인 경우 보기 집합 | 아래 보기 형식 참조
solutions | array | 현재 작성된 첨삭의 리스트 | 아래 첨삭 형식 참조

- 보기 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 보기번호 | -
context | String | 보기 문자 | - 

- 첨삭 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
score | int | 해당문제에 대한 평가 점수 | 0~10의 값
context | String | 문제에 대한 평가 및 풀이 | -
img | file | 평가 및 풀이 이미지 | -

**Comment by ssky10** [comment]
수정했습니다. 죄송합니다...ㅠ

**Comment by golony6449** [comment]
코드 리뷰 후 배포 완료했습니다.

확인 후 피드백 부탁드립니다.

https://gitlab.com/golony6449/go100/tree/develop/url_design
