### ISSUE TITLE
[API] Q&A게시글 목록 가져오기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#45]
# API 요청
1. 요청 API 주소 : api/qna/getpostlist
2. 서비스 내용 : Q&A 게시글 목록 가져오기
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | string | |말안해도 잘알거라고 믿음
class_id| int | 학급 구분자 | |

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
list | List | 반환 내용 | 아래 테이블 참조

* list

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
post_id | int | 게시글 구분자 | -
isAnswerd | boolean | 답변 여부 파악 | -
title | string | qna 제목 | -
reg_date | datetime | 게시날 | -

**Comment by golony6449** [comment]
구현완료했습니다.

확인 후 피드백 부탁드립니다.

**Comment by yg3988** [comment]
@golony6449 문제 없이 잘 됩니다.
