### ISSUE TITLE
[API] Q&A 게시글 가져오기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#46]
# API 요청
1. 요청 API 주소 :  api/qna/getqnapost
2. 서비스 내용 : qna 게시글 가져오기
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class_id | int | 학급 번호 | 학급 구별자
post_id | int | 게시글 번호 | 게시글 구별자

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
title | string | 글 제목 | -
isAnswered | boolean | 답변 여부 | T/F
user_id | string | 글 쓴 이름 | -
date | datetime | 글 게시 날짜 | -
q_contents | string | 물음 내용 | -
a_contents | string | 답변 내용 | -

**Comment by Y0ung-i1** [comment]
@golony6449 구현 및 문서 완료

**Comment by golony6449** [comment]
코드 리뷰한 뒤, 서버에 적용했습니다.

확인 후 피드백 부탁드립니다.

https://gitlab.com/golony6449/go100/tree/develop/url_design

**Comment by yg3988** [comment]
죄송합니다 user_id => user_name으로 수정 부탁드리겠습니다.

**Comment by yg3988** [comment]
a_contents 내용 수정 부탁드리겠습니다.
string 타입이 아니라 list타입으로

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_id | string | 답변 게시자 id | -
contents | string | 답변 내용 | -

늦게 요청해서 죄송합니다.
