### ISSUE TITLE
[API] Class 생성

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#54]
# API 요청
1. 요청 API 주소 : `api/classroom/createClass`
2. 서비스 내용 : Class를 생성합니다.
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인 유저 토큰값 | -
name | String | Class이름 | -
desc | String | Class 한줄 설명 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | bool | 성공여부 | -

**Comment by golony6449** [comment]
API 구현 완료했습니다.

확인 후 피드백 부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/classroom_url_design.md
