### ISSUE TITLE
[API] Q&A 글 작성하기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#55]
# API 요청
1. 요청 API 주소 : `api/qna/writepost`
2. 서비스 내용 : 묻는 글 쓰기
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class_id | int | 학급 구별자 | -
user_name | string | 글쓴이 정보 | 묻는 이 이름
title | string | 글 제목 | -
content | string | 물음 내용 | -
date | datetime | 게시날 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
isSuccess | boolean | 글 작성 성공 여부 | True 글 작성 성공, False 글 작성 실패

**Comment by golony6449** [comment]
늦어서 죄송합니다.
개발은 예전에 마쳤으나, 노티가 늦었습니다. 

구현완료 및 서버 적용 완료했습니다.

확인부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/classroom_url_design.md

**Comment by golony6449** [comment]
`date` 값은 따로 사용하지 않고, 서버시간을 가져와서 적용하기 때문에 문서에서 삭제했습니다.

**Comment by yg3988** [comment]
예, 알겠습니다.

**Comment by yg3988** [comment]
적용 확인했습니다 이상없습니다.
