### ISSUE TITLE
[API] 학급 소개글 작성

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#58]
# API 요청
1. 요청 API 주소 : `api/classroom/setclassroomabout`
2. 서비스 내용 : 학급 소개글 작성
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인된 사용자 | -
class_id | int | 학급 구별자 | -
about | String | 학급 소개글 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
isSuccess | boolean | 적용 성공 여부 | -

**Comment by Y0ung-i1** [comment]
@yg3988 학급 소개글 작성이 아닌 학급 소개글 수정으로 변경하여 문서 작업 및 데이터작성하였습니다.

**Comment by golony6449** [comment]
코드리뷰 마치고, 서버에 배포했습니다.

확인부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/classroom_url_design.md
