### ISSUE TITLE
[API] 알맞은 학생 찾기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#59]
# API 요청
1. 요청 API 주소 : `api/classroom/findstudent`
2. 서비스 내용 : 학생 등록에 필요한 학생 찾기 api
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
stu_id | string | 학생 ID | 학급에 등록할 학생의 아이디 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
list | List | 학생 리스트 | 해당 아이디를 사용하는 학생 리스트 | -

* list

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_id | string | 학생 ID |  시스템에 등록된 아이디 | -
user_name | string | 학생 이름 | 시스템에 등록된 학생이름 | -

**Comment by golony6449** [comment]
구현 후 서버에 적용을 마쳤습니다.

키워드는 대소문자를 구분합니다.

**Comment by golony6449** [comment]
https://gitlab.com/golony6449/go100/blob/develop/url_design/auth_url_design.md

**Comment by yg3988** [comment]
404에러 나서 확인해봤는데 url이 바뀐건가요?
 url_design의 auth 문서에서 사라졌는데 확인 부탁드리겠습니다.
