### ISSUE TITLE
[API] 라이브 퀴즈 목록 가져오기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#60]
# API 요청
1. 요청 API 주소 : `api/classroom/livequizList`
2. 서비스 내용 : 교사의 경우 현재 만들어둔 전체 라이브퀴즈 리스트를, 학생의 경우 현재 활성화된 라이브퀴즈 리스트를 받아옴
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인된 사용자 토큰 | - 
class | int | 클래스 고유번호 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | bool | 성공여부 | -
list | array | 생성된 라이브퀴즈 목록 | 해당 수업교사의 경우 현재 만들어둔 전체 라이브퀴즈 리스트 / 학생의 경우 현재 활성화된 라이브퀴즈 리스트

 - 라이브퀴즈 목록 형식

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
code | int | 라이브퀴즈 고유번호 | -
title | string| 라이브퀴즈 명 | -
quizzes_num | int | 해당 라이브퀴즈 문제 set개수 | -
date | int | 생성된 날짜 | -

**Comment by golony6449** [comment]
구현완료했습니다

문서 참고 부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/live_quiz_url_design.md
