### ISSUE TITLE
[API] 라이브퀴즈 삭제하기

### ISSUE THREAD

**Issue by ssky10** [ssky10/go100#61]
# API 요청
1. 요청 API 주소 : `api/classroom/livequizDelet`
2. 서비스 내용 : 해당 라이브퀴즈 set을 삭제함
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | String | 로그인된 사용자 토큰 | - 
class | int | 클래스 고유번호 | -
code | int | 라이브퀴즈 고유번호 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
status | bool | 성공여부 | -

**Comment by golony6449** [comment]
구현완료 및 서버적용 끝났습니다.

자세한 내용은 문서 참조 부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/live_quiz_url_design.md

<b>`class_id`는 사용하지 않아서 문서상에서 제외시켰습니다</b>
