### ISSUE TITLE
[API] 학급 정보  가져오기

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#63]
# API 요청
1. 요청 API 주소 : `api/classrooom/getclassinfo`
2. 서비스 내용 :  학급 명, 유저 ID 가져오기
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_token | string | 유저 token | -
class_id | int | 학급 구별자 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
class_name | string | 학급 이름 | -

**Comment by yg3988** [comment]
@Y0ung-i1 수정 부탁드립니다.
학급 이름 전달이 되지 않습니다.
classinfo에서 description(학급 소개글)도 반환 하도록 수정 부탁드리겠습니다.
가급적 description은 about이라는 이름으로 반환부탁드리겠습니다.

**Comment by golony6449** [comment]
![image](https://user-images.githubusercontent.com/10653376/59003702-fbd0bb80-8851-11e9-9885-f6b3295e1324.png)

학급 이름은 정상적으로 수신되는 것으로 보입니다.

학습 소개글은 누락되어있습니다. `about` 명칭으로 전송하도록 수정하겠습니다.

죄송합니다.

**Comment by yg3988** [comment]
수정 감사합니다. 성공적으로 적용됐습니다. 이슈 닫습니다.
