### ISSUE TITLE
[API] 유저 생성 API

### ISSUE THREAD

**Issue by yg3988** [ssky10/go100#66]
# API 요청
1. 요청 API 주소 : `api/auth/createuser`
2. 서비스 내용 : 유저 생성을 위한 API
3. 전송데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
user_name | string | 사용자 ID | -
first_name | string | 사용자 이름 | -
last_name | string | 사용자 성 | -
password | string | 비밀번호 | -

4. 반환데이터

이름(key) | 자료형(Value Type)|데이터 내용(Context)|비고
------------ | ------------- | ------------- | -------------
isSuccess | booleans | 성공여부 | -

**Comment by yg3988** [comment]
@Y0ung-i1 확인 부탁

**Comment by golony6449** [comment]
구현 후 서버 적용완료되었습니다.

확인부탁드립니다.

https://gitlab.com/golony6449/go100/blob/develop/url_design/auth_url_design.md#%ED%95%99%EC%83%9D-%EC%B6%94%EA%B0%80-api

**Comment by yg3988** [comment]
@golony6449 성공적으로 적용됬습니다. 이슈 닫습니다.
